name: recipe_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  url_launcher: ^6.1.5

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  english_words: ^3.1.0
  http: ^0.13.5
  circle_nav_bar: ^1.0.2
  equatable: ^2.0.3
  animate_do: ^2.1.0
  shared_preferences: ^2.0.15
  theme_manager: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Loginpage/lock_1.gif
    - assets/images/Loginpage/lock_2.gif
    - assets/images/Loginpage/lock.png
